services:
  # leases:
  #   build: 
  #     context: .
  #     dockerfile: ./apps/leases/Dockerfile
  #     target: development
  #   command: npm run start:dev leases
  #   env_file:
  #     - ./apps/leases/.env
  #   depends_on:
  #     - mongodb-primary
  #     - mongodb-secondary
  #     - mongodb-arbiter
  #   volumes:
  #     - .:/user/src/app
  #     - /user/src/app/node_modules
  #   ports:
  #     - '3000:3000'
  rabbitmq:
    image: rabbitmq
    ports: 
      - '5672:5672' 
      
  